name: Workflow Agendado de 5 em 5 Horas

on:
  schedule:
    # Roda a cada 5 horas (minuto 0 das horas 0, 5, 10, 15, 20)
    - cron: '0 */5 * * *'

jobs:
  executar-tarefa:
    runs-on: ubuntu-latest
    steps:
      # O actions/checkout garante que o código mais recente seja baixado
      - name: Baixar o push mais recente
        uses: actions/checkout@v4

      - name: Executar script
        run: |
          echo "Executando com o código mais recente do repositório..."
env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}